=== TechConf/OldCodeMash2015/Get Shipping with Docker/Lab 3/dockerfiles/wls12.1.2/wls12120/oracle_common/common/sql/wlsservices/ComponentInfo.dtd
<?xml version="1.0" encoding="UTF-8" ?>
<!ENTITY % commonDTD SYSTEM "RCUCommon.dtd">
%commonDTD;
<!ELEMENT ComponentInfo (Display?, PrefixSettings?, Component*, ComponentConfigFiles?,  PrerequisiteDescriptor*, ExecutionDescriptor?, FatalErrors?, IgnorableErrors?)>
<!ATTLIST ComponentInfo
        VERSION CDATA #IMPLIED
        TYPE CDATA #IMPLIED
        RESOURCE_BUNDLE_PACKAGE CDATA #IMPLIED>
<!ELEMENT PrefixSettings (DetectQuery*)>
<!ATTLIST PrefixSettings 
          USE_SCHEMA_PREFIX (TRUE|FALSE) "TRUE"
          USE_TABLESPACE_PREFIX (TRUE|FALSE) "TRUE">
<!ELEMENT ComponentConfigFiles (ConfigFile*)>
<!ATTLIST ConfigFile
          ID CDATA #REQUIRED>
<!ELEMENT ConfigFile (#PCDATA)>
<!ELEMENT Component (ValidIfSet?, ValidIf?, Display, RepositoryConfigFile?, DetectQuery*, SchemaVersion?, SchemaUser?, AdditionalSchemaUser*, Dependents?, DatabaseName?, Tablespaces?, CustomVariables?)>
<!ATTLIST Component
        ID CDATA #REQUIRED
        PROGRESS_UNITS CDATA #IMPLIED 
        IS_GROUPING_COMPONENT  (TRUE|FALSE) "FALSE"
        DEFAULT_SELECTED (TRUE|FALSE) "FALSE"
        CHILD_OF CDATA #IMPLIED 
        MANDATORY_SELECTED (TRUE|FALSE) "FALSE">
<!ELEMENT Display (#PCDATA)>
<!ATTLIST Display
        NLS_ID CDATA #IMPLIED>
<!ELEMENT RepositoryConfigFile (#PCDATA)>
<!ELEMENT DetectQuery (#PCDATA)>
<!ATTLIST DetectQuery
        OPERATION (CREATE|DROP|DATALOAD) 'CREATE'
        TYPE (ORACLE|SQLSERVER|IBMDB2) 'ORACLE'>
<!ELEMENT SchemaVersion (#PCDATA)>
<!ELEMENT SchemaUser (#PCDATA)>
<!ATTLIST SchemaUser
        USER_EDITABLE (TRUE|FALSE) "TRUE"
        PREFIXABLE (TRUE|FALSE) "TRUE"
        IS_CREATED  (TRUE|FALSE) "TRUE"
        MAX_LENGTH CDATA "30">
<!ELEMENT AdditionalSchemaUser (#PCDATA)>
<!ATTLIST AdditionalSchemaUser
        STARTS_WITH_SCHEMA_USER (TRUE|FALSE) "TRUE" >
<!ELEMENT Dependents (Dependent*)>
<!ELEMENT Dependent (#PCDATA)>
<!ATTLIST Dependent
        COMPONENT_ID CDATA #REQUIRED
        ALT_COMPONENT_ID CDATA #IMPLIED>
<!ELEMENT DatabaseName (#PCDATA)>
<!ELEMENT Tablespaces (Tablespace*)>
<!ATTLIST Tablespace TYPE (DEFAULT_TABLESPACE|TEMPORARY_TABLESPACE|ADDITIONAL_TABLESPACE1|ADDITIONAL_TABLESPACE2|ADDITIONAL_TABLESPACE3|ADDITIONAL_TABLESPACE4|ADDITIONAL_TABLESPACE5|ADDITIONAL_TABLESPACE6|ADDITIONAL_TABLESPACE7|ADDITIONAL_TABLESPACE8|ADDITIONAL_TABLESPACE9|ADDITIONAL_TABLESPACE10|ADDITIONAL_TABLESPACE11|ADDITIONAL_TABLESPACE12|ADDITIONAL_TABLESPACE13|ADDITIONAL_TABLESPACE14|ADDITIONAL_TABLESPACE15|ADDITIONAL_TABLESPACE16|ADDITIONAL_TABLESPACE17|ADDITIONAL_TABLESPACE18|ADDITIONAL_TABLESPACE19|ADDITIONAL_TABLESPACE20|ADDITIONAL_TABLESPACE21|ADDITIONAL_TABLESPACE22|ADDITIONAL_TABLESPACE23|ADDITIONAL_TABLESPACE24|ADDITIONAL_TABLESPACE25|ADDITIONAL_TABLESPACE26|ADDITIONAL_TABLESPACE27|ADDITIONAL_TABLESPACE28|ADDITIONAL_TABLESPACE29|ADDITIONAL_TABLESPACE30|ADDITIONAL_TABLESPACE31) "DEFAULT_TABLESPACE">
<!ELEMENT Tablespace (Prompt, TablespaceName)>
<!ELEMENT Prompt (#PCDATA)>
<!ATTLIST Prompt NLS_ID CDATA #IMPLIED>
<!ELEMENT TablespaceName (#PCDATA)>
<!ELEMENT CustomVariables (Variable*)>
<!ATTLIST Variable
          TYPE (STRING|NUMBER|PASSWORD|EXISTING_PASSWORD|FILE) "STRING"
          MAX_LENGTH CDATA "30"
          MIN_LENGTH CDATA "0"
          MAX_VALUE CDATA #IMPLIED
          MIN_VALUE CDATA #IMPLIED
          OPERATION (CREATE|DROP|BOTH) "BOTH"
          DEFAULT_VALUE CDATA "">
<!ELEMENT Variable (Name,Display)>
<!ELEMENT Name (#PCDATA)>

=== TechConf/OldCodeMash2015/Get Shipping with Docker/Lab 3/dockerfiles/wls12.1.2/wls12120/oracle_common/common/sql/svctbl/svctbl_ComponentInfo.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!-- STB -->
<!DOCTYPE ComponentInfo SYSTEM "ComponentInfo.dtd">
<ComponentInfo>
 <Component ID="STB" PROGRESS_UNITS="50" MANDATORY_SELECTED="TRUE" CHILD_OF="AS_COMMON">
  <ValidIf DBTYPE="ORACLE"/>
  <Display NLS_ID="STB_ID">ServiceTable</Display>
  <RepositoryConfigFile>%RCU_HOME%/../oracle_common/common/sql/svctbl/svctbl.xml</RepositoryConfigFile>
  <DetectQuery>select owner from schema_version_registry where mr_type = 'STB' and mrc_name = '%PREFIX_NAME%' and status in ('VALID','LOADED')</DetectQuery>
  <DetectQuery OPERATION='DATALOAD'>select owner from schema_version_registry where mr_type = 'STB' and mrc_name = '%PREFIX_NAME%' and status = 'LOADED'</DetectQuery>
  <DetectQuery OPERATION='DROP'>select owner from schema_version_registry where mr_type = 'STB' and mrc_name = '%PREFIX_NAME%'</DetectQuery>
  <SchemaUser USER_EDITABLE="FALSE">STB</SchemaUser>
  <DatabaseName>STB</DatabaseName> 
  <Tablespaces>
    <Tablespace TYPE="DEFAULT_TABLESPACE">
       <Prompt NLS_ID="DEFAULT_TABLESPACE">Default Tablespace</Prompt>
       <TablespaceName>STB</TablespaceName>
    </Tablespace>
    <Tablespace TYPE="TEMPORARY_TABLESPACE">
       <Prompt NLS_ID="TEMPORARY_TABLESPACE">Temporary Tablespace</Prompt>
       <TablespaceName>IAS_TEMP</TablespaceName>
    </Tablespace>
  </Tablespaces>
 </Component>
 <Component ID="STB" PROGRESS_UNITS="50" MANDATORY_SELECTED="TRUE" CHILD_OF="AS_COMMON">
   <ValidIf DBTYPE="EBR"/>
   <Display NLS_ID="STB_ID">ServiceTable</Display>
   <RepositoryConfigFile>%RCU_HOME%/../oracle_common/common/sql/svctbl/svctbl.xml</RepositoryConfigFile>
   <DetectQuery>select owner from schema_version_registry where mr_type = 'STB' and mrc_name = '%PREFIX_NAME%' and status in ('VALID','LOADED')</DetectQuery>
   <DetectQuery OPERATION='DATALOAD'>select owner from schema_version_registry where mr_type = 'STB' and mrc_name = '%PREFIX_NAME%' and status = 'LOADED'</DetectQuery>
   <DetectQuery OPERATION='DROP'>select owner from schema_version_registry where mr_type = 'STB' and mrc_name = '%PREFIX_NAME%'</DetectQuery>
   <SchemaUser USER_EDITABLE="FALSE">STB</SchemaUser>
   <DatabaseName>STB</DatabaseName> 
   <Tablespaces>
     <Tablespace TYPE="DEFAULT_TABLESPACE">
        <Prompt NLS_ID="DEFAULT_TABLESPACE">Default Tablespace</Prompt>
        <TablespaceName>STB</TablespaceName>
     </Tablespace>
     <Tablespace TYPE="TEMPORARY_TABLESPACE">
        <Prompt NLS_ID="TEMPORARY_TABLESPACE">Temporary Tablespace</Prompt>
        <TablespaceName>IAS_TEMP</TablespaceName>
     </Tablespace>
   </Tablespaces>
 </Component>
 <Component ID="STB" PROGRESS_UNITS="50" MANDATORY_SELECTED="TRUE" CHILD_OF="AS_COMMON">
   <ValidIf DBTYPE="SQLSERVER"/>
   <Display NLS_ID="STB_ID">ServiceTable</Display>
   <RepositoryConfigFile>%RCU_HOME%/../oracle_common/common/sql/svctbl/svctbl.xml</RepositoryConfigFile>
   <DetectQuery>select owner from schema_version_registry where mr_type = 'STB' and mrc_name = '%PREFIX_NAME%' and status in ('VALID','LOADED')</DetectQuery>
   <DetectQuery OPERATION='DATALOAD'>select owner from schema_version_registry where mr_type = 'STB' and mrc_name = '%PREFIX_NAME%' and status = 'LOADED'</DetectQuery>
   <DetectQuery OPERATION='DROP'>select owner from schema_version_registry where mr_type = 'STB' and mrc_name = '%PREFIX_NAME%'</DetectQuery>
   <SchemaUser USER_EDITABLE="FALSE">STB</SchemaUser>
   <DatabaseName>STB</DatabaseName> 
 </Component>
<Component ID="STB" PROGRESS_UNITS="50" MANDATORY_SELECTED="TRUE" CHILD_OF="AS_COMMON">
  <ValidIf DBTYPE="IBMDB2"/>
  <Display NLS_ID="STB_ID">ServiceTable</Display>
  <RepositoryConfigFile>%RCU_HOME%/../oracle_common/common/sql/svctbl/svctbl.xml</RepositoryConfigFile>
  <DetectQuery>select owner from nullid.schema_version_registry where mr_type = 'STB' and mrc_name = '%PREFIX_NAME%' and status in ('VALID','LOADED')</DetectQuery>
  <DetectQuery OPERATION='DATALOAD'>select owner from nullid.schema_version_registry where mr_type = 'STB' and mrc_name = '%PREFIX_NAME%' and status = 'LOADED'</DetectQuery>
  <DetectQuery OPERATION='DROP'>select owner from nullid.schema_version_registry where mr_type = 'STB' and mrc_name = '%PREFIX_NAME%'</DetectQuery>
  <SchemaUser USER_EDITABLE="FALSE">STB</SchemaUser>
  <DatabaseName>STB</DatabaseName> 
  <Tablespaces>
    <Tablespace TYPE="DEFAULT_TABLESPACE">
       <Prompt NLS_ID="DEFAULT_TABLESPACE">Default Tablespace</Prompt>
       <TablespaceName>STB</TablespaceName>
    </Tablespace>
    <Tablespace TYPE="TEMPORARY_TABLESPACE">
       <Prompt NLS_ID="TEMPORARY_TABLESPACE">Temporary Tablespace</Prompt>
       <TablespaceName>IAS_TEMP</TablespaceName>
    </Tablespace>
  </Tablespaces>
</Component>
<Component ID="STB" PROGRESS_UNITS="50" MANDATORY_SELECTED="TRUE" CHILD_OF="AS_COMMON">
  <ValidIf DBTYPE="MYSQL"/>
  <Display NLS_ID="STB_ID">ServiceTable</Display>
  <RepositoryConfigFile>%RCU_HOME%/../oracle_common/common/sql/svctbl/svctbl.xml</RepositoryConfigFile>
  <DetectQuery>select owner from schema_version_registry where mr_type = 'STB' and mrc_name = '%PREFIX_NAME%' and status in ('VALID','LOADED')</DetectQuery>
  <DetectQuery OPERATION='DATALOAD'>select owner from schema_version_registry where mr_type = 'STB' and mrc_name = '%PREFIX_NAME%' and status = 'LOADED'</DetectQuery>
  <DetectQuery OPERATION='DROP'>select owner from schema_version_registry where mr_type = 'STB' and mrc_name = '%PREFIX_NAME%'</DetectQuery>
  <SchemaUser USER_EDITABLE="FALSE">STB</SchemaUser>
  <DatabaseName>STB</DatabaseName> 
 </Component>
</ComponentInfo> 
<!-- End Of STB -->

=== TechConf/OldCodeMash2015/Get Shipping with Docker/Lab 3/dockerfiles/wls12.1.2/wls12120/oracle_common/common/sql/wlsservices/wlsservices_ComponentInfo.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE ComponentInfo SYSTEM "ComponentInfo.dtd">
<!-- WLS -->
<ComponentInfo>
  <Component ID="WLS" PROGRESS_UNITS="30" CHILD_OF="AS_COMMON">
      <ValidIf DBTYPE="ORACLE" /> 
      <Display NLS_ID="WLS_ID">WebLogic Services</Display>
      <RepositoryConfigFile>%RCU_HOME%/../oracle_common/common/sql/wlsservices/wlsservices.xml</RepositoryConfigFile>
      <DetectQuery>select owner from schema_version_registry where mr_type = 'WLS' and mrc_name = '%PREFIX_NAME%' and status in ('VALID','LOADED')</DetectQuery>
      <DetectQuery OPERATION='DATALOAD'>select owner from schema_version_registry where mr_type = 'WLS' and mrc_name = '%PREFIX_NAME%' and status = 'LOADED'</DetectQuery>
      <DetectQuery OPERATION='DROP'>select owner from schema_version_registry where mr_type = 'WLS' and mrc_name = '%PREFIX_NAME%'</DetectQuery>
      <SchemaUser>WLS</SchemaUser>
      <DatabaseName>WLS</DatabaseName>
      <Tablespaces>
        <Tablespace TYPE="DEFAULT_TABLESPACE">
           <Prompt NLS_ID="DEFAULT_TABLESPACE">WLS Services Default Tablespace</Prompt>
           <TablespaceName>WLS</TablespaceName>
        </Tablespace>
        <Tablespace TYPE="TEMPORARY_TABLESPACE">
           <Prompt NLS_ID="TEMPORARY_TABLESPACE">WLS Services Temporary Tablespace</Prompt>
           <TablespaceName>IAS_TEMP</TablespaceName>
        </Tablespace>
      </Tablespaces>
  </Component>
  <Component ID="WLS" PROGRESS_UNITS="30" CHILD_OF="AS_COMMON">
      <ValidIf DBTYPE="EBR" /> 
      <Display NLS_ID="WLS_ID">WebLogic Services</Display>
      <RepositoryConfigFile>%RCU_HOME%/../oracle_common/common/sql/wlsservices/wlsservices.xml</RepositoryConfigFile>
      <DetectQuery>select owner from schema_version_registry where mr_type = 'WLS' and mrc_name = '%PREFIX_NAME%' and status in ('VALID','LOADED')</DetectQuery>
      <DetectQuery OPERATION='DATALOAD'>select owner from schema_version_registry where mr_type = 'WLS' and mrc_name = '%PREFIX_NAME%' and status = 'LOADED'</DetectQuery>
      <DetectQuery OPERATION='DROP'>select owner from schema_version_registry where mr_type = 'WLS' and mrc_name = '%PREFIX_NAME%'</DetectQuery>
      <SchemaUser>WLS</SchemaUser>
      <DatabaseName>WLS</DatabaseName>
      <Tablespaces>
        <Tablespace TYPE="DEFAULT_TABLESPACE">
           <Prompt NLS_ID="DEFAULT_TABLESPACE">WLS Services Default Tablespace</Prompt>
           <TablespaceName>WLS</TablespaceName>
        </Tablespace>
        <Tablespace TYPE="TEMPORARY_TABLESPACE">
           <Prompt NLS_ID="TEMPORARY_TABLESPACE">WLS Services Temporary Tablespace</Prompt>
           <TablespaceName>IAS_TEMP</TablespaceName>
        </Tablespace>
      </Tablespaces>
  </Component>
  <Component ID="WLS" PROGRESS_UNITS="30" CHILD_OF="AS_COMMON">
      <ValidIf DBTYPE="SQLSERVER"/>
      <Display NLS_ID="WLS_ID">WebLogic Services</Display>
      <RepositoryConfigFile>%RCU_HOME%/../oracle_common/common/sql/wlsservices/wlsservices.xml</RepositoryConfigFile>
      <DetectQuery>select owner from schema_version_registry where mr_type = 'WLS' and mrc_name = '%PREFIX_NAME%' and status = 'VALID'</DetectQuery>
      <DetectQuery OPERATION='DROP'>select owner from schema_version_registry where mr_type = 'WLS' and mrc_name = '%PREFIX_NAME%'</DetectQuery>
      <SchemaUser>WLS</SchemaUser>
      <DatabaseName>WLS</DatabaseName>
  </Component>
  <Component ID="WLS" PROGRESS_UNITS="30" CHILD_OF="AS_COMMON">
      <ValidIf DBTYPE="IBMDB2"/>
      <Display NLS_ID="WLS_ID">WebLogic Services</Display>
      <RepositoryConfigFile>%RCU_HOME%/../oracle_common/common/sql/wlsservices/wlsservices.xml</RepositoryConfigFile>
      <DetectQuery>select owner from nullid.schema_version_registry where mr_type = 'WLS' and mrc_name = '%PREFIX_NAME%' and status = 'VALID'</DetectQuery>
      <DetectQuery OPERATION='DROP'>select owner from nullid.schema_version_registry where mr_type = 'WLS' and mrc_name = '%PREFIX_NAME%'</DetectQuery>
      <SchemaUser>WLS</SchemaUser>
      <DatabaseName>WLS</DatabaseName>
      <Tablespaces>
         <Tablespace TYPE="DEFAULT_TABLESPACE">
         <Prompt NLS_ID="DEFAULT_TABLESPACE">Default Tablespace</Prompt>
         <TablespaceName>WLS</TablespaceName>
      </Tablespace>
      <Tablespace TYPE="TEMPORARY_TABLESPACE">
         <Prompt NLS_ID="TEMPORARY_TABLESPACE">Temporary Tablespace</Prompt>
         <TablespaceName>IAS_TEMP</TablespaceName>
      </Tablespace>
    </Tablespaces>
  </Component>
  <Component ID="WLS" PROGRESS_UNITS="30" CHILD_OF="AS_COMMON">
      <ValidIf DBTYPE="MYSQL"/>
      <Display NLS_ID="WLS_ID">WebLogic Services</Display>
      <RepositoryConfigFile>%RCU_HOME%/../oracle_common/common/sql/wlsservices/wlsservices.xml</RepositoryConfigFile>
      <DetectQuery>select owner from schema_version_registry where mr_type = 'WLS' and mrc_name = '%PREFIX_NAME%' and status = 'VALID'</DetectQuery>
    <DetectQuery OPERATION='DROP'>select owner from schema_version_registry where mr_type = 'WLS' and mrc_name = '%PREFIX_NAME%'</DetectQuery>
      <SchemaUser>WLS</SchemaUser>
      <DatabaseName>WLS</DatabaseName>
  </Component>
</ComponentInfo>
<!-- End of WLS -->
