=== TechConf/OldCodeMash2015/Get Shipping with Docker/Lab 3/dockerfiles/wls12.1.2/wls12120/oracle_common/common/sql/wlsservices/Storage.dtd
<?xml version="1.0" encoding="UTF-8" ?>
<!ELEMENT StorageAttributes ( ComponentStorageFiles?, TablespaceAttributes*)>
<!ELEMENT ComponentStorageFiles (StorageFile*)>
<!ATTLIST StorageFile
          ID CDATA #REQUIRED>
<!ELEMENT StorageFile (#PCDATA)>
<!ELEMENT TablespaceAttributes (Type?,DefaultTemp?,BlockSize?,ExtentSize?,PageSize?,AutoResize?,IncreaseSize?,MaxSize?,Bigfile?,AutoSegmentSpaceManagement?, DatafilesList)>
<!ATTLIST TablespaceAttributes
	NAME CDATA #REQUIRED>
<!ELEMENT Type (#PCDATA)>
<!ELEMENT DefaultTemp (#PCDATA)>
<!ELEMENT BlockSize (#PCDATA)>
<!ELEMENT ExtentSize (#PCDATA)>
<!ELEMENT PageSize (#PCDATA)>
<!ATTLIST PageSize
        UNIT (KB|NoUnit) 'KB'>
<!ELEMENT AutoResize (#PCDATA)>
<!ELEMENT IncreaseSize (#PCDATA)>
<!ATTLIST IncreaseSize
        UNIT (KB|MB|GB) 'MB'>
<!ELEMENT MaxSize (#PCDATA)>
<!ATTLIST MaxSize
        UNIT (KB|MB|GB) 'MB'>
<!ELEMENT Bigfile (#PCDATA)>
<!ELEMENT AutoSegmentSpaceManagement (#PCDATA)>
<!ELEMENT DatafilesList (DatafileAttributes+)>
<!ELEMENT DatafileAttributes (Size, Reuse?, AutoExtend?, Increment?, Maxsize?)>
<!ATTLIST DatafileAttributes
 ID CDATA #REQUIRED>
<!ELEMENT Size (#PCDATA)>
<!ATTLIST Size
	UNIT (KB|MB|GB) 'MB'>
<!ELEMENT Reuse (#PCDATA)>
<!ELEMENT AutoExtend (#PCDATA)>
<!ELEMENT Increment (#PCDATA)>
<!ATTLIST Increment
	UNIT (KB|MB|GB) 'KB'>
<!ELEMENT Maxsize (#PCDATA)>
<!ATTLIST Maxsize
	UNIT (KB|MB|GB) 'MB'>

=== TechConf/OldCodeMash2015/Get Shipping with Docker/Lab 3/dockerfiles/wls12.1.2/wls12120/oracle_common/common/sql/wlsservices/wlsservices_Storage.xml
<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE StorageAttributes SYSTEM "Storage.dtd"><!-- WLS --><StorageAttributes>
  <TablespaceAttributes NAME="WLS" >    <Type>      REGULAR    </Type>  
    <DatafilesList>      <DatafileAttributes ID="%DATAFILE_LOCATION%/wlsservices.dbf">        <Size UNIT="MB">          60        </Size>        <Reuse>          True        </Reuse>        <AutoExtend>          True        </AutoExtend>          <Increment UNIT="MB">          10         </Increment>      </DatafileAttributes>    </DatafilesList>    </TablespaceAttributes></StorageAttributes>
<!-- End of WLS -->
